build:
    # first, build the build image
  build_image:
    image: docker:1.9
    commands:
      - docker build -t komand/python-plugin .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  build_project:
    image: komand/python-plugin:latest
    commands:
      - make all
      - make test
notify:
  slack:
     webhook_url: $$SLACK_URL 
     channel: devstatus
     username: drone
